### ISSUE TITLE
$Data::Dumper::Terse=1 ruins whitespacing

### ISSUE THREAD

**Issue by bittrine** [perlpunk/HTML-Template-Compiled#10]
Setting $Data::Dumper::Terse to true results in replacing all whitespaces in generated html with SCALAR(0x...). You definitely should localize dumper variables in your code before using it.
P.S. Thanks for the good job and useful module!

**Comment by perlpunk** [comment]
Interesting, thanks!
I localized the Data::Dumper vars I use, but didn't think of localizing the other ones to their defaults.

Fixed now, I think I'll upload at least a developer release this weekend.

**Comment by perlpunk** [comment]
Uploaded 1.003 to CPAN
