### ISSUE TITLE
CPAN Pull Request Challenge

### ISSUE THREAD

**Issue by caipre** [perlpunk/HTML-Template-Compiled#3]
Hey @perlpunk, 

I'm participating in the [CPAN Pull Request Challenge](http://blogs.perl.org/users/neilb/2014/12/take-the-2015-cpan-pull-request-challenge.html) and was assigned this project for January. I saw that there was already one outstanding issue; does that seem like a reasonable one to tackle or might there be something else that's more pressing? I'm an intermediate level Perl programmer, and happy to learn more. I'll be reading about this project to get some background and hopefully will have some PRs to you soon. :)

Thanks!

**Comment by perlpunk** [comment]
You can have a look at it =)
IIRC I had a quick look and saw that this might not be trivial, so I decided to look at it later. (And didn't have time so far)
