### ISSUE TITLE
Globalstack is corrupted when trying to TMPL_LOOP on undefined values.

### ISSUE THREAD

**Issue by rpv-tomsk** [perlpunk/HTML-Template-Compiled#8]
Hi Tina!

I have found another issue in H::T::C.

HTC generates the following code for TMPL_LOOP:

if (my @array = eval { @${ \$t->try_global($$C, 'UNEXISTENT') } } ){
$t->pushGlobalstack( $$C);
[...cut ...]
}
} # end loop
$t->popGlobalstack;

So, there are conditions exists then popGlobalstack() will be called without appropriate pushGlobalstack() and globalstack gets corrupted.

I made pull request (https://github.com/perlpunk/HTML-Template-Compiled/pull/7) with patch to fix this issue.  Please look into it.

Thanks!

Regards,
Pavel.

**Comment by perlpunk** [comment]
good catch, thanks. I'm usually not using globalstack, so I never saw an issue. I merged the PR!
